Repository gardener/cert-management, pull requests merged in 2020-07, with the labels that each got.

#33 make propagation timeout configurable and use it for DNSEntry TTL
  charts/cert-management/templates/deployment.yaml
  charts/cert-management/values.yaml
  hack/generateChartOptions.py
  pkg/cert/legobridge/certificate.go
  pkg/cert/legobridge/dnscontrollerprovider.go
  pkg/controller/issuer/certificate/reconciler.go
  pkg/controller/issuer/controller.go
  pkg/controller/issuer/core/const.go
Labels: area/robustness, needs/ok-to-test, platform/alicloud, priority/critical

#34 updated controller-manager-library for startup check issue
  go.mod
  go.sum
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/controller.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm

#36 Update channel name for posting release notes
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm
