Repository gardener/cert-management, pull requests merged in 2020-11, with the labels that each got.

#45 Update README
  README.md
  examples/20-issuer-ca.yaml
Labels: reviewed/lgtm, size/m

#46 cleanup orphan outdated certificate secrets
  build/Dockerfile
  pkg/cert/legobridge/certificate.go
  pkg/controller/issuer/certificate/reconciler.go
Labels: needs/ok-to-test, size/s

#50 Moving cert management docs from /documentation
  docs/installation/setup.md
  docs/usage/request_cert.md
Labels: needs/ok-to-test, reviewed/lgtm, size/l

#51 Revert "Moving cert management docs from /documentation"
  docs/installation/setup.md
  docs/usage/request_cert.md
Labels: needs/review, needs/second-opinion, reviewed/ok-to-test, size/l

#49 common name annotation for services and ingresses
  README.md
  examples/40-ingress-echoheaders.yaml
  examples/40-service-loadbalancer.yaml
  pkg/cert/source/controller.go
  pkg/cert/source/defaults.go
  pkg/controller/source/ingress/handler.go
Labels: needs/ok-to-test, size/m

#52 update to go v1.15.5
  build/Dockerfile
Labels: needs/ok-to-test, needs/review, size/xs

#54 renew certificate if its certificate secret is invalid/corrupt instead of going to state error
  pkg/controller/issuer/certificate/reconciler.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
