Repository gardener/cert-management, pull requests merged in 2021-06, with the labels that each got.

#77 Allow issuers on target cluster
  README.md
  VERSION
  charts/cert-management/templates/crds.yaml
  charts/cert-management/templates/deployment.yaml
  charts/cert-management/values.yaml
  examples/10-crds.yaml
  go.mod
  go.sum
  pkg/apis/cert/crds/cert.gardener.cloud_certificates.yaml
  pkg/apis/cert/crds/zz_generated_crds.go
  pkg/apis/cert/v1alpha1/certificate.go
  pkg/apis/cert/v1alpha1/zz_generated.deepcopy.go
  pkg/cert/legobridge/certificate.go
  pkg/cert/legobridge/dnscontrollerprovider.go
  pkg/cert/legobridge/reguser.go
  pkg/cert/metrics/metrics.go
  pkg/cert/source/controller.go
  pkg/cert/utils/domainrange.go
  pkg/cert/utils/issuerinfo.go
  pkg/cert/utils/issuerkey.go
  pkg/cert/utils/utils_certificate.go
  pkg/controller/issuer/acme/handler.go
  pkg/controller/issuer/ca/handler.go
  pkg/controller/issuer/certificate/backupsecret.go
  pkg/controller/issuer/certificate/reconciler.go
  pkg/controller/issuer/controller.go
  pkg/controller/issuer/core/associatedObjects.go
  pkg/controller/issuer/core/const.go
  pkg/controller/issuer/core/issuerDNSSelections.go
  pkg/controller/issuer/core/quotas.go
  pkg/controller/issuer/core/referencedSecrets.go
  pkg/controller/issuer/core/referencedSecrets_test.go
  pkg/controller/issuer/core/state.go
  pkg/controller/issuer/core/support.go
  pkg/controller/issuer/reconciler.go
  pkg/controller/issuer/revocation/reconciler.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/controller.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/lease.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/watches/constraints.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/watches/interface.go
  vendor/github.com/gardener/controller-manager-library/pkg/resources/informers.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#78 Update GH PR template
  .github/pull_request_template.md
Labels: needs/ok-to-test, needs/review, size/xs

#79 using configmaps and leases for leader election
  README.md
  charts/cert-management/templates/clusterrole.yaml
  charts/cert-management/templates/deployment.yaml
  charts/cert-management/templates/role.yaml
  charts/cert-management/values.yaml
  cmd/cert-controller-manager/main.go
  go.mod
  go.sum
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/lease/config.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/lease/lease.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/syncer.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/s
