Repository gardener/cert-management, pull requests merged in 2021-02, with the labels that each got.

#60 add metrics for certificate secrets
  README.md
  pkg/cert/legobridge/certificate.go
  pkg/cert/legobridge/reguser.go
  pkg/cert/metrics/metrics.go
  pkg/controller/issuer/certificate/backupsecret.go
  pkg/controller/issuer/certificate/reconciler.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#61 support external account binding for ACME DigiCert
  charts/cert-management/templates/crds.yaml
  examples/10-crds.yaml
  examples/21-issuer-acme-eab.yaml
  hack/check-cert-secret.sh
  pkg/apis/cert/crds/cert.gardener.cloud_issuers.yaml
  pkg/apis/cert/crds/zz_generated_crds.go
  pkg/apis/cert/v1alpha1/issuer.go
  pkg/apis/cert/v1alpha1/zz_generated.deepcopy.go
  pkg/cert/legobridge/certificate.go
  pkg/cert/legobridge/dnscontrollerprovider.go
  pkg/cert/legobridge/reguser.go
  pkg/cert/utils/dns_utils.go
  pkg/controller/issuer/acme/handler.go
  pkg/controller/issuer/certificate/backupsecret.go
  pkg/controller/issuer/certificate/reconciler.go
  pkg/controller/issuer/certificate/utils.go
  pkg/controller/issuer/core/state.go
  pkg/controller/issuer/core/support.go
  pkg/controller/issuer/revocation/reconciler.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#62 Move type registration to main init
  cmd/cert-controller-manager/main.go
  pkg/apis/cert/v1alpha1/register.go
  test/functional/basics.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
