Repository gardener/cert-management, pull requests merged in 2021-07, with the labels that each got.

#80 Fixed links
  README.md
Labels: needs/ok-to-test, needs/review, size/xs

#82 Update README.md
  README.md
Labels: needs/ok-to-test, needs/review, size/xs

#81 [ACME] Fix account registration on issuer secret update
  build/Dockerfile
  go.mod
  pkg/cert/legobridge/cakeypair.go
  pkg/cert/legobridge/certificate.go
  pkg/cert/legobridge/dnscontrollerprovider.go
  pkg/cert/legobridge/pki.go
  pkg/cert/legobridge/reguser.go
  pkg/cert/utils/utils_certificate.go
  pkg/controller/issuer/acme/handler.go
  pkg/controller/issuer/ca/handler.go
  pkg/controller/issuer/certificate/backupsecret.go
  pkg/controller/issuer/certificate/reconciler.go
  pkg/controller/issuer/core/support.go
  pkg/controller/issuer/core/wrappedregistration.go
  pkg/controller/issuer/revocation/reconciler.go
  test/functional/basics.go
  test/functional/config/config.go
  test/functional/config/utils.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#83 fix for migration of certificate-hash
  pkg/controller/issuer/acme/handler.go
  pkg/controller/issuer/certificate/backupsecret.go
  pkg/controller/issuer/certificate/reconciler.go
  pkg/controller/issuer/core/state.go
  pkg/controller/issuer/core/support.go
Labels: needs/ok-to-test, needs/review, size/m

#84 fix panic on failed secret update on hash migration
  pkg/controller/issuer/certificate/reconciler.go
Labels: needs/ok-to-test, needs/review, size/xs

#85 fix nil pointer dereference in RememberAltIssuerSecret
  pkg/controller/issuer/core/support.go
Labels: needs/ok-to-test, needs/review, size/xs
