Repository gardener/cert-management, pull requests merged in 2023-08, with the labels that each got.

#133 Update charts CRDs to latest version
  Makefile
  charts/cert-management/templates/cert.gardener.cloud_certificaterevocations.yaml
  charts/cert-management/templates/cert.gardener.cloud_certificates.yaml
  charts/cert-management/templates/cert.gardener.cloud_issuers.yaml
  charts/cert-management/templates/crds-v1.yaml
  charts/cert-management/templates/crds-v1beta1.yaml
  vendor/github.com/gardener/controller-manager-library/hack/run-in.sh
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl

#134 Bump golang from 1.20.6 to 1.20.7
  build/Dockerfile
Labels: needs/review, reviewed/ok-to-test, size/xs

#135 Fix optional deployment of CRDs
  charts/cert-management/templates/cert.gardener.cloud_certificaterevocations.yaml
  charts/cert-management/templates/cert.gardener.cloud_certificates.yaml
  charts/cert-management/templates/cert.gardener.cloud_issuers.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#136 Add helm labels to CRDs
  Makefile
  charts/cert-management/templates/cert.gardener.cloud_certificaterevocations.yaml
  charts/cert-management/templates/cert.gardener.cloud_certificates.yaml
  charts/cert-management/templates/cert.gardener.cloud_issuers.yaml
  hack/copy-crds.sh
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#138 Fix edge case of inconsistent certificate/secret: request certificate in this case
  pkg/controller/issuer/certificate/reconciler.go
  test/functional/basics.go
Labels: needs/ok-to-test, needs/review, size/s
