Repository gardener/cert-management, pull requests merged in 2024-07, with the labels that each got.

#199 Bump cert-manager to version 1.14.7
  go.mod
  go.sum
Labels: kind/task, needs/ok-to-test, size/M, cla: yes

#230 remove csr, cert and keys from example files
  examples/20-issuer-ca.yaml
  examples/30-cert-csr.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, size/XS, cla: yes, approved, lgtm

#234 fix creating certificates with a given csr referencing a ca issuer
  pkg/cert/legobridge/certificate.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, size/S, cla: yes, approved, lgtm
