Repository gardener/cert-management, pull requests merged in 2024-02, with the labels that each got.

#160 Grant dnsentries permission in clusterrole
  charts/cert-management/templates/clusterrole.yaml
  charts/cert-management/templates/role.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#162 Using common code generation scripts
  hack/generate-code
Labels: needs/ok-to-test

#150 Certificates without common name (simplified certificates for domain names longer than 64 chars)
  README.md
  go.mod
  go.sum
  pkg/apis/cert/v1alpha1/types.go
  pkg/cert/legobridge/certificate.go
  pkg/cert/legobridge/pki.go
  pkg/cert/source/reconciler.go
  pkg/cert/utils/utils_certificate.go
  pkg/controller/issuer/core/support_test.go
  test/functional/basics.go
Labels: kind/api-change, needs/ok-to-test, needs/review, needs/second-opinion, reviewed/do-not-merge, size/m

#163 Make repo compliant
  .reuse/dep5
  CONTRIBUTING.md
  LICENSE
  LICENSES/Apache-2.0.txt
  LICENSES/BSD-2-Clause.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/CC-BY-4.0.txt
  LICENSES/ISC.txt
  LICENSES/MIT.txt
  README.md
  hack/LICENSE_BOILERPLATE.txt
  pkg/apis/cert/crds/zz_generated_crds.go
  pkg/apis/cert/v1alpha1/zz_generated.deepcopy.go
  pkg/client/cert/clientset/versioned/clientset.go
  pkg/client/cert/clientset/versioned/fake/clientset_generated.go
  pkg/client/cert/clientset/versioned/fake/doc.go
  pkg/client/cert/clientset/versioned/fake/register.go
  pkg/client/cert/clientset/versioned/scheme/doc.go
  pkg/client/cert/clientset/versioned/scheme/register.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/cert_client.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/certificate.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/certificaterevocation.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/doc.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/fake/doc.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/fake/fake_cert_client.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/fake/fake_certificate.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/fake/fake_certificaterevocation.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/fake/fake_issuer.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/generated_expansion.go
  pkg/client/cert/clientset/versioned/typed/cert/v1alpha1/issuer.go
  pkg/client/cert/informers/externalversions/cert/interface.go
  pkg/client/cert/informers/externalversions/cert/v1alpha1/certificate.go
  pkg/client/cert/informers/externalversions/cert/v1alpha1/certificaterevocation.go
  pkg/client/cert/informers/externalversions/cert/v1alpha1/interface.go
  pkg/client/cert/informers/externalversions/cert/v1alpha1/issuer.go
  pkg/client/cert/informers/externalversions/factory.go
  pkg/client/cert/informers/externalversions/generic.go
  pkg/client/cert/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/cert/listers/cert/v1alpha1/certificate.go
  pkg/client/cert/listers/cert/v1alpha1/certificaterevocation.go
  pkg/client/cert/listers/cert/v1alpha1/expansion_generated.go
  pkg/client/cert/listers/cert/v1alpha1/issuer.go
Labels: needs/ok-to-test, reviewed/lgtm, area/ipcei
