Repository gardener/cert-management, pull requests merged in 2024-08, with the labels that each got.

#240 Refactoring: introduce issuer key interface to simplify rewrite
  pkg/cert/legobridge/certificate.go
  pkg/cert/legobridge/delegatingprovider.go
  pkg/cert/legobridge/reguser.go
  pkg/cert/metrics/metrics.go
  pkg/cert/utils/issuerinfo.go
  pkg/cert/utils/issuerkey.go
Labels: kind/task, needs/ok-to-test, reviewed/ok-to-test, size/M, cla: yes, approved, lgtm

#257 Replace registry image repository
  hack/kind/registry/base/registry.yaml
Labels: kind/task, needs/ok-to-test, size/XS, cla: yes

#281 Publish Helm charts as OCI artifacts
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, kind/task, needs/ok-to-test, reviewed/ok-to-test, size/S, area/os, cla: yes, approved, lgtm
