Repository gardener/cert-management, pull requests merged in 2025-08, with the labels that each got.

#549 Add write permissions for release workflow
  .github/workflows/release.yaml
Labels: kind/task, size/XS, cla: yes, approved, lgtm

#556 chore: Use Renovate preset for grouping Go updates
  renovate.json5
Labels: area/dev-productivity, kind/enhancement, size/XS, cla: yes, approved, lgtm

#560 Add `set -o pipefail` to react on `make generate` failure
  .github/workflows/build.yaml
Labels: kind/task, size/XS, cla: yes, approved, lgtm

#561 Add a build badge to the README.md
  README.md
Labels: kind/enhancement, size/XS, cla: yes, approved, lgtm

#563 chore: Bump version to v0.18.0-dev
  VERSION
  charts/cert-management/values.yaml
Labels: kind/task, size/XS, cla: yes, approved, lgtm
