Repository gardener/cert-management, pull requests merged in 2025-07, with the labels that each got.

#520 migrate pipelines to GitHub-Actions
  .ci/pipeline_definitions
  .ci/prepare_release
  .github/actions/prepare-release/action.yaml
  .github/workflows/build.yaml
  .github/workflows/non-release.yaml
  .github/workflows/release.yaml
  .ocm/base-component.yaml
Labels: kind/task, needs/ok-to-test, reviewed/ok-to-test, size/L, cla: yes, lgtm

#524 feat: Add SAN fields in Certificate spec
  README.md
  charts/cert-management/templates/cert.gardener.cloud_certificates.yaml
  examples/30-cert-ca.yaml
  examples/30-cert-selfsigned.yaml
  pkg/apis/cert/crds/cert.gardener.cloud_certificates.yaml
  pkg/apis/cert/crds/zz_generated_crds.go
  pkg/apis/cert/v1alpha1/types.go
  pkg/apis/cert/v1alpha1/zz_generated.deepcopy.go
  pkg/certman2/apis/cert/crd-cert.gardener.cloud_certificates.yaml
  pkg/controller/issuer/certificate/reconciler.go
  pkg/controller/issuer/certificate/utils.go
  pkg/controller/issuer/certificate/utils_test.go
  pkg/shared/legobridge/certificate.go
  pkg/shared/legobridge/pki.go
  test/integration/controller/issuer/certificate_test.go
Labels: kind/api-change, kind/task, size/XL, cla: yes, approved, lgtm

#536 export testresults as inlined ocm-resource
  .github/workflows/build.yaml
Labels: kind/task, size/M, cla: yes, approved, lgtm, skip-review
