Repository gardener/cert-management, pull requests merged in 2025-03, with the labels that each got.

#428 Make `pkg/certman2` independent from CML and internal packages
  Makefile
  cmd/cert-controller-manager/main.go
  pkg/apis/cert/register.go
  pkg/apis/cert/v1alpha1/register.go
  pkg/cert/client/scheme.go
  pkg/cert/source/controller.go
  pkg/cert/utils/issuerinfo_test.go
  pkg/cert/utils/issuerkey.go
  pkg/cert/utils/utils_certificate.go
  pkg/cert/utils/utils_certificate_test.go
  pkg/cert/utils/utils_issuer.go
  pkg/certman2/apis/cert/register.go
  pkg/certman2/client/scheme.go
  pkg/certman2/controller/certificate/add.go
  pkg/certman2/controller/certificate/add_test.go
  pkg/certman2/controller/issuer/controlplane/acme/handler.go
  pkg/certman2/controller/issuer/controlplane/acme/handler_test.go
  pkg/certman2/controller/issuer/controlplane/ca/handler.go
  pkg/certman2/controller/issuer/controlplane/ca/handler_test.go
  pkg/certman2/controller/source/common/certinput_collector.go
  pkg/certman2/core/keys.go
  pkg/certman2/core/support.go
  pkg/certman2/core/utils.go
  pkg/controller/issuer/acme/handler.go
  pkg/controller/issuer/ca/handler.go
  pkg/controller/issuer/certificate/backupsecret.go
  pkg/controller/issuer/certificate/reconciler.go
  pkg/controller/issuer/certificate/utils.go
  pkg/controller/issuer/controller.go
  pkg/controller/issuer/core/support.go
  pkg/controller/issuer/revocation/reconciler.go
  pkg/shared/const.go
  pkg/shared/dns_utils.go
  pkg/shared/dns_utils_test.go
  pkg/shared/issuerinfo.go
  pkg/shared/issuerkeyitf.go
  pkg/shared/legobridge/cakeypair.go
  pkg/shared/legobridge/cakeypair_test.go
  pkg/shared/legobridge/certificate.go
  pkg/shared/legobridge/certificate_test.go
  pkg/shared/legobridge/delegatingprovider.go
  pkg/shared/legobridge/delegatingprovider_test.go
  pkg/shared/legobridge/dnscontrollerprovider.go
  pkg/shared/legobridge/dnsrecordprovider.go
  pkg/shared/legobridge/keystores.go
  pkg/shared/legobridge/keystores_test.go
  pkg/shared/legobridge/legobridge_suite_test.go
  pkg/shared/legobridge/pending.go
  pkg/shared/legobridge/pending_test.go
  pkg/shared/legobridge/pki.go
  pkg/shared/legobridge/pki_test.go
  pkg/shared/legobridge/reguser.go
  pkg/shared/metrics/metrics.go
  pkg/shared/shared_suite_test.go
  pkg/shared/utils_certificate.go
  pkg/shared/utils_certificate_test.go
  test/certman2/integration/controller/issuer/issuer_test.go
  test/functional/basics.go
  test/functional/config/utils.go
Labels: kind/task, needs/ok-to-test, reviewed/ok-to-test, cla: yes, approved, lgtm, size/XXL, ok-to-test

#433 Drop linked package "github.com/gardener/cert-management/pkg/certman2/apis/cert/v1alpha1"
  pkg/certman2/apis/cert/v1alpha1
  pkg/certman2/client/scheme.go
  pkg/certman2/controller/certificate/add.go
  pkg/certman2/controller/certificate/reconciler.go
  pkg/certman2/controller/certificate/reconciler_delete.go
  pkg/certman2/controller/certificate/reconciler_reconcile.go
  pkg/certman2/controller/issuer/controlplane/acme/handler.go
  pkg/certman2/controller/issuer/controlplane/acme/handler_test.go
  pkg/certman2/controller/issuer/controlplane/add.go
  pkg/certman2/controller/issuer/controlplane/ca/handler.go
  pkg/certman2/controller/issuer/controlplane/ca/handler_test.go
  pkg/certman2/controller/issuer/controlplane/reconciler.go
  pkg/certman2/controller/source/common/certinput.go
  pkg/certman2/controller/source/common/reconcilerbase.go
  pkg/certman2/controller/source/ingress/reconciler_test.go
  pkg/certman2/controller/source/istio_gateway/reconciler_test.go
  pkg/certman2/controller/source/k8s_gateway/reconciler_test.go
  pkg/certman2/controller/source/service/reconciler_test.go
  pkg/certman2/core/issuerDNSSelections.go
  pkg/certman2/core/referencedSecrets_test.go
  pkg/certman2/core/state.go
  pkg/certman2/core/support.go
  test/certman2/integration/controller/issuer/issuer_test.go
  test/certman2/integration/controller/source/source_test.go
Labels: kind/cleanup, needs/ok-to-test, size/M, cla: yes, approved, lgtm

#442 ci: Unify `make format`
  .ci/pipeline_definitions
  .ci/verify
  Makefile
Labels: kind/enhancement, needs/ok-to-test, size/M, cla: yes, approved, lgtm

#443 docs: Document triggering a manual certificate renewal
  README.md
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, size/S, cla: yes, approved, lgtm

#445 Drop tests from verify-extended target
  Makefile
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, size/XS, cla: yes, approved, lgtm

#447 Add condition for deployment of CRDs in Helm charts
  charts/cert-management/templates/cert.gardener.cloud_certificaterevocations.yaml
  charts/cert-management/templates/cert.gardener.cloud_certificates.yaml
  charts/cert-management/templates/cert.gardener.cloud_issuers.yaml
  hack/copy-crds.sh
Labels: kind/bug, needs/ok-to-test, reviewed/ok-to-test, size/M, cla: yes, approved, lgtm
