Repository gardener/cert-management, pull requests merged in 2025-04, with the labels that each got.

#451 fix: Key algorithm and bit size in self-signed certs from CA
  pkg/controller/issuer/certificate/reconciler.go
  pkg/shared/legobridge/certificate.go
  pkg/shared/legobridge/pki.go
  pkg/shared/legobridge/pki_test.go
  test/integration/controller/issuer/certificate_test.go
Labels: kind/bug, needs/ok-to-test, reviewed/ok-to-test, size/L, cla: yes, approved, lgtm

#455 refactor: Fix typo in function name
  pkg/controller/issuer/certificate/reconciler.go
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, size/XS, cla: yes, approved, lgtm

#456 Update base image to `debian12`
  Dockerfile
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, size/XS, cla: yes, approved, lgtm

#460 fix: ClusterRole needs dnsrecord permissions when issuerUseDnsrecords is true
  charts/cert-management/templates/clusterrole.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/ok-to-test, size/XS, cla: yes, approved, lgtm

#458 Drop pipeline step `check` as redundant
  .ci/check
  .ci/pipeline_definitions
Labels: kind/cleanup, needs/ok-to-test, size/S, cla: yes, approved, lgtm

#462 Integrate `generate-renovate-ignore-deps.sh` into `make generate`
  Makefile
  hack/generate-renovate-ignore-deps.sh
  renovate.json5
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, size/L, cla: yes, approved, lgtm

#468 Forbid privilege escalations for component containers
  charts/cert-management/templates/deployment.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, size/XS, cla: yes, approved, lgtm

#478 ci: Run integration tests in one command
  Makefile
Labels: kind/test, needs/ok-to-test, reviewed/ok-to-test, size/XS, cla: yes, approved, lgtm

#485 Drop tools dependency `sigs.k8s.io/controller-runtime/tools/setup-envtest`
  go.mod
  go.sum
  hack/tools.go
  renovate.json5
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, size/XS, cla: yes, approved, lgtm
