Repository gardener/cert-management, pull requests merged in 2025-01, with the labels that each got.

#384 Support `DNSRecord.spec.class` by annotation `cert.gardener.cloud/dnsrecord-class`
  examples/30-cert-simple.yaml
  pkg/cert/legobridge/certificate.go
  pkg/cert/legobridge/dnsrecordprovider.go
  pkg/cert/source/controller.go
  pkg/cert/source/utils.go
  pkg/controller/issuer/certificate/reconciler.go
Labels: kind/enhancement, needs/ok-to-test, size/S, cla: yes, approved, lgtm

#391 Add Unit Tests to Utils
  pkg/cert/legobridge/cakeypair_test.go
  pkg/cert/source/reconciler.go
  pkg/cert/utils/dns_utils_test.go
  pkg/cert/utils/domainrange_test.go
  pkg/cert/utils/issuerkey_test.go
  pkg/cert/utils/utils_certificate_test.go
  pkg/cert/utils/utils_mod.go
  pkg/cert/utils/utils_mod_test.go
  pkg/controller/issuer/certificate/reconciler.go
Labels: kind/test, needs/ok-to-test, size/XL, cla: yes, approved, lgtm, ok-to-test

#396 Add make target for executing unit tests with test coverage
  .gitignore
  Makefile
Labels: kind/enhancement, needs/ok-to-test, size/XS, cla: yes, approved, lgtm, ok-to-test
